Minor fixes
DanSheps/netbox-secretstore pull request #90
Opened 2022-08-28 12:59 UTC by abhi1693

- Removed `importlib` dependency. With the version that NetBox supports, I do not see any reason to add this dependency
- Fixed docstring for `get-session-key`
- Fixed swagger for `get-session-key`

2022-09-21 16:28 UTC, abhi1693 commented
@DanSheps Could you please review this?

2022-09-21 17:12 UTC, DanSheps requested changes

2022-09-21 17:18 UTC, abhi1693 commented on netbox_secretstore/__init__.py
> +    base_url = 'secrets'
If you call from pynetbox like this

```
nb.plugins.netbox_secretstore.secrets.get(id=1)
```

It translates that to the URL like
```
/api/netbox-secretstore/secrets/1/
```

I did submit a fix but that was not the right to patch the code.

2022-11-18 17:22 UTC, abhi1693 commented
I'm going to close this PR in favour of our internal plugin that we are working on

2022-11-18 17:22 UTC, closed without merging